[tool.black]
line-length = 100
target-version = ["py312"]


[tool.ruff]
line-length = 100
target-version = "py312"
exclude = [
  ".git",
  "__pycache__",
  ".venv",
  "venv",
]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "B", "UP"]
ignore = ["E501"]
fixable = ["ALL"]

[tool.ruff.format]
quote-style = "preserve"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
